package releaseverify

import (
	"errors"
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

const publishReleaseNotesRun = `set -euo pipefail
args=(release create "$TAG" --title "$TAG" --notes-file "$RUNNER_TEMP/release-notes.md" --verify-tag)
# Prerelease when the SemVer tag carries a pre-release suffix (e.g. -beta.1).
case "$TAG" in *-*) args+=(--prerelease) ;; esac
gh "${args[@]}"`

// VerifyReleaseNotesWorkflow keeps prose generation outside the signing workflow and constrains
// the model to the audited local categorizer before GitHub Release publication.
func VerifyReleaseNotesWorkflow(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	root, err := parseYAML(data)
	if err != nil {
		return err
	}
	if err := verifyUses(root); err != nil {
		return err
	}
	if err := verifyOnlyKeys(root, "release notes workflow", "name", "on", "permissions", "concurrency", "jobs"); err != nil {
		return err
	}
	if scalarValue(root, "name") != "Release notes" {
		return errors.New("release notes workflow name must be Release notes")
	}
	if err := verifyReleaseTrigger(root); err != nil {
		return err
	}
	if err := verifyReleaseNotesPermissions(root); err != nil {
		return err
	}
	if err := verifyReleaseNotesConcurrency(root); err != nil {
		return err
	}
	jobs, err := requiredMap(root, "jobs")
	if err != nil {
		return err
	}
	if len(jobs.Content) != 2 || jobs.Content[0].Value != "publish-notes" {
		return errors.New("release notes workflow must contain only the audited publish-notes job")
	}
	job, err := requiredMap(jobs, "publish-notes")
	if err != nil {
		return err
	}
	if err := verifyOnlyKeys(job, "release notes job", "name", "runs-on", "steps"); err != nil {
		return err
	}
	if scalarValue(job, "runs-on") != "ubuntu-latest" {
		return errors.New("release notes job must run on ubuntu-latest")
	}
	return verifyReleaseNotesSteps(job)
}

func verifyReleaseNotesPermissions(root *yaml.Node) error {
	permissions, err := requiredMap(root, "permissions")
	if err != nil {
		return err
	}
	if len(permissions.Content) != 2 || scalarValue(permissions, "contents") != "write" {
		return errors.New("release notes workflow may grant only contents: write")
	}
	return nil
}

func verifyReleaseNotesConcurrency(root *yaml.Node) error {
	concurrency, err := requiredMap(root, "concurrency")
	if err != nil {
		return err
	}
	if err := verifyOnlyKeys(concurrency, "release notes concurrency", "group", "cancel-in-progress"); err != nil {
		return err
	}
	if scalarValue(concurrency, "group") != "release-notes-${{ github.ref }}" || scalarValue(concurrency, "cancel-in-progress") != "false" {
		return errors.New("release notes publication must serialize per tag without cancellation")
	}
	return nil
}

func verifyReleaseNotesSteps(job *yaml.Node) error {
	steps, err := requiredSequence(job, "steps")
	if err != nil {
		return err
	}
	if len(steps.Content) != 4 {
		return fmt.Errorf("release notes job must contain exactly 4 audited steps, found %d", len(steps.Content))
	}
	for index, step := range steps.Content {
		if _, exists := mappingValue(step, "if"); exists {
			return fmt.Errorf("release notes step %d must not be conditional", index+1)
		}
		if _, exists := mappingValue(step, "continue-on-error"); exists {
			return fmt.Errorf("release notes step %d must fail closed", index+1)
		}
	}
	if err := verifyOnlyKeys(steps.Content[0], "release notes checkout step", "name", "uses"); err != nil {
		return err
	}
	if actionName(steps.Content[0]) != "actions/checkout" || strings.TrimSpace(scalarValue(steps.Content[0], "run")) != "" {
		return errors.New("release notes step 1 must check out the tagged commit")
	}
	if err := verifyOnlyKeys(steps.Content[1], "release notes Go setup step", "name", "uses", "with"); err != nil {
		return err
	}
	if actionName(steps.Content[1]) != "actions/setup-go" || strings.TrimSpace(scalarValue(steps.Content[1], "run")) != "" {
		return errors.New("release notes step 2 must set up Go")
	}
	setup, err := requiredMap(steps.Content[1], "with")
	if err != nil || len(setup.Content) != 4 || scalarValue(setup, "go-version-file") != "go.mod" || scalarValue(setup, "cache") != "false" {
		return errors.New("release notes Go setup must use go.mod without a mutable cache")
	}
	generate := steps.Content[2]
	if err := verifyOnlyKeys(generate, "release notes generator step", "name", "env", "shell", "run"); err != nil {
		return err
	}
	if scalarValue(generate, "shell") != "bash" {
		return errors.New("release notes generator must use exact bash semantics")
	}
	if strings.TrimSpace(scalarValue(generate, "run")) != `./scripts/generate-release-notes.sh "$TAG" "$RUNNER_TEMP/release-notes.md"` {
		return errors.New("release notes must be generated by the audited local helper")
	}
	generateEnv, err := requiredMap(generate, "env")
	if err != nil {
		return err
	}
	requiredGenerateEnv := map[string]string{
		"GH_TOKEN":                   "${{ github.token }}",
		"OPENROUTER_RELEASE_API_KEY": "${{ secrets.OPENROUTER_RELEASE_API_KEY }}",
		"RELEASE_NOTES_MODEL":        "${{ vars.RELEASE_NOTES_MODEL }}",
		"TAG":                        "${{ github.ref_name }}",
	}
	if len(generateEnv.Content) != len(requiredGenerateEnv)*2 {
		return errors.New("release notes generator environment contains unaudited values")
	}
	for name, want := range requiredGenerateEnv {
		if got := scalarValue(generateEnv, name); got != want {
			return fmt.Errorf("release notes generator %s = %q, want %q", name, got, want)
		}
	}
	publish := steps.Content[3]
	if err := verifyOnlyKeys(publish, "release notes publication step", "name", "env", "shell", "run"); err != nil {
		return err
	}
	if scalarValue(publish, "shell") != "bash" || strings.TrimSpace(scalarValue(publish, "run")) != publishReleaseNotesRun {
		return errors.New("release notes must publish the validated file through the audited command")
	}
	publishEnv, err := requiredMap(publish, "env")
	if err != nil || len(publishEnv.Content) != 4 || scalarValue(publishEnv, "GH_TOKEN") != "${{ github.token }}" || scalarValue(publishEnv, "TAG") != "${{ github.ref_name }}" {
		return errors.New("release notes publisher must receive only the workflow token and tag")
	}
	return nil
}

func actionName(step *yaml.Node) string {
	return strings.SplitN(scalarValue(step, "uses"), "@", 2)[0]
}
