package settings

import (
	"fmt"
	"sort"
	"strings"
)

// groupTitles maps a Group to its human heading for the generated docs (and,
// later, the Settings IA). Kept beside the registry so a new group surfaces here.
var groupTitles = map[Group]string{
	GroupMediaServer:   "Connections — Media server",
	GroupRequester:     "Connections — Requester",
	GroupTunarr:        "Connections — Tunarr",
	GroupTMDB:          "Connections — TMDB",
	GroupGeneral:       "General",
	GroupAI:            "AI",
	GroupChannels:      "Channels & playback",
	GroupPlayout:       "Playout",
	GroupFiller:        "Filler / commercials",
	GroupBackup:        "Backup",
	GroupNotifications: "Notifications",
	GroupUsersSecurity: "Users & security",
	GroupSSO:           "Single sign-on",
	GroupImages:        "Images",
	GroupAdvanced:      "Advanced",
}

// Markdown renders the registry as docs/configuration.md (config-design §2: the
// generated contract, mirrored by design.md §15). Deterministic — groups in
// declaration order, keys in declaration order — so the CI drift check is stable.
// A blank line at EOF keeps the file gofmt-of-markdown clean.
func (r *Registry) Markdown() []byte {
	var b strings.Builder
	b.WriteString("# Loomarr configuration reference\n\n")
	b.WriteString("<!-- GENERATED by `make config-docs` from the settings registry. DO NOT EDIT. -->\n")
	b.WriteString("<!-- The registry (internal/settings/declared.go) is the contract; design.md §15 is the human mirror. -->\n\n")
	b.WriteString("Every setting resolves **`env > database > default`** (config-design §3). ")
	b.WriteString("An env var that is set **pins** the value and locks its UI field. ")
	b.WriteString("Secrets are encrypted before database persistence, masked on read, and never echoed (config-design §4).\n\n")
	b.WriteString("## Bootstrap — Database secret protection\n\n")
	b.WriteString("`LOOMARR_ENCRYPTION_KEY` supplies a 32-byte installation key as unpadded base64url; ")
	b.WriteString("`LOOMARR_ENCRYPTION_KEY_FILE` points to a file containing the same value. Set only one. ")
	b.WriteString("When neither is set, Loomarr creates `/data/encryption.key` with mode `0600`. ")
	b.WriteString("Every PostgreSQL replica must use the same key, and database backups require it to recover stored credentials.\n\n")
	b.WriteString("To replace the installation key, supply the new current key and provide the old key for one boot through ")
	b.WriteString("`LOOMARR_ENCRYPTION_KEY_PREVIOUS` or `LOOMARR_ENCRYPTION_KEY_PREVIOUS_FILE`. ")
	b.WriteString("Remove the previous-key input after Loomarr starts successfully.\n\n")

	for _, g := range r.Groups() {
		title := groupTitles[g]
		if title == "" {
			title = string(g)
		}
		b.WriteString("## " + title + "\n\n")
		b.WriteString("| Setting (env) | Kind | Default | Notes |\n")
		b.WriteString("| --- | --- | --- | --- |\n")
		for _, s := range r.ByGroup(g) {
			b.WriteString(row(s))
		}
		b.WriteString("\n")
	}
	return []byte(b.String())
}

// row renders one setting as a table row. Secrets show "(secret)" for the default
// (never a value); enums list their set; flags (advanced / required-for) append
// to the notes so the mirror stays faithful to the declaration.
func row(s Setting) string {
	def := defaultCell(s)
	notes := s.Doc
	var tags []string
	if s.Advanced {
		tags = append(tags, "advanced")
	}
	if s.Required != FeatureNone {
		tags = append(tags, "required for "+string(s.Required))
	}
	if s.Apply == ApplyRestart {
		tags = append(tags, "applies after restart")
	}
	if s.Kind == KindEnum {
		tags = append(tags, "one of: "+strings.Join(s.EnumValues(), " | "))
	}
	if len(tags) > 0 {
		notes = notes + " _(" + strings.Join(tags, "; ") + ")_"
	}
	return fmt.Sprintf("| `%s` (`%s`) | %s | %s | %s |\n",
		s.Key, s.EnvVar, s.Kind, def, escapePipes(notes))
}

// defaultCell renders a setting's default for the table. Secrets never print a
// value; an empty default is "—".
func defaultCell(s Setting) string {
	if s.IsSecret() {
		return "(secret)"
	}
	str := ValueString(s.Default)
	if str == "" {
		return "—"
	}
	return "`" + str + "`"
}

// escapePipes keeps a doc string with a literal | from breaking the table.
func escapePipes(s string) string { return strings.ReplaceAll(s, "|", "\\|") }

// keysForDocs is a stable sorted key list (used by the drift test to assert the
// generated doc covers exactly the registry).
func keysForDocs(r *Registry) []string {
	out := make([]string, 0, len(r.All()))
	for _, s := range r.All() {
		out = append(out, s.Key)
	}
	sort.Strings(out)
	return out
}
