package api

import (
	"bytes"
	"context"
	"net/http"
	"runtime"
	"time"

	"github.com/danielgtaylor/huma/v2"

	"github.com/loomarr/loomarr/docs"
	"github.com/loomarr/loomarr/internal/buildinfo"
	"github.com/loomarr/loomarr/internal/store"
)

// registerHelp mounts the in-app Help + system-info routes (§13). Both are readable by
// any authenticated user: Help is documentation, and the version is what a member quotes
// in a bug report.
func (s *Server) registerHelp(api huma.API) {
	huma.Register(api, withRole(huma.Operation{
		OperationID: "list-docs", Method: http.MethodGet, Path: "/v1/docs",
		Summary:     "List the embedded help pages",
		Description: "The Help section's table of contents (§13). Pages ship inside the binary, so Help works air-gapped.",
		Tags:        []string{"help"},
	}, RoleMember), s.listDocs)

	huma.Register(api, withRole(huma.Operation{
		OperationID: "get-doc", Method: http.MethodGet, Path: "/v1/docs/{slug}",
		Summary:     "Read one help page as markdown",
		Description: "Returns raw markdown, not HTML: the frontend renders it and searches it client-side (§7.2), which needs the source rather than a rendered blob.",
		Tags:        []string{"help"},
	}, RoleMember), s.getDoc)

	rawOp[diagramInput](api, bytesResponse(huma.Operation{
		OperationID: "get-doc-diagram", Method: http.MethodGet, Path: "/v1/docs/diagrams/{name}",
		Summary: "Read one help diagram",
		Description: "A diagram a help page shows, as SVG. It ships inside the binary, so Help's " +
			"diagrams work air-gapped. Load it only as an image: it is served sandboxed.",
		Tags: []string{"help"},
	}, "The diagram.", "image/svg+xml"), RoleMember, serveDiagram)

	rawOp[screenshotInput](api, bytesResponse(huma.Operation{
		OperationID: "get-doc-screenshot", Method: http.MethodGet, Path: "/v1/docs/screenshots/{name}",
		Summary: "Read one help screenshot",
		Description: "A screenshot a help page shows, as WebP. It ships inside the binary, so Help's " +
			"screenshots work air-gapped.",
		Tags: []string{"help"},
	}, "The screenshot.", "image/webp"), RoleMember, serveScreenshot)

	huma.Register(api, withRole(huma.Operation{
		OperationID: "system-version", Method: http.MethodGet, Path: "/v1/system/version",
		Summary:     "Version and readiness of this instance",
		Description: "What the operator quotes in a bug report, plus the readiness /v1/readyz reports. The probes stay unauthenticated for orchestrators (RolePublic); this is their authenticated twin, carrying the build and schema detail a probe has no business returning.",
		Tags:        []string{"system"},
	}, RolePublic), s.systemVersion)
}

// DocSummary is one entry in the Help table of contents.
type DocSummary struct {
	Slug  string `json:"slug" example:"troubleshooting"`
	Title string `json:"title" example:"Troubleshooting"`
}

type listDocsOutput struct {
	Body struct {
		Docs []DocSummary `json:"docs"`
	}
}

func (s *Server) listDocs(_ context.Context, _ *struct{}) (*listDocsOutput, error) {
	out := &listDocsOutput{}
	pages := docs.Pages()
	out.Body.Docs = make([]DocSummary, 0, len(pages))
	for _, p := range pages {
		out.Body.Docs = append(out.Body.Docs, DocSummary{Slug: p.Slug, Title: p.Title})
	}
	return out, nil
}

type getDocInput struct {
	Slug string `path:"slug" example:"troubleshooting"`
}
type getDocOutput struct {
	Body struct {
		Slug     string `json:"slug"`
		Title    string `json:"title"`
		Markdown string `json:"markdown"`
	}
}

func (s *Server) getDoc(_ context.Context, in *getDocInput) (*getDocOutput, error) {
	page, ok := docs.Get(in.Slug)
	if !ok {
		return nil, errNotFound("Help page not found", "That help page doesn't exist — it may have been moved or renamed.")
	}
	out := &getDocOutput{}
	out.Body.Slug, out.Body.Title, out.Body.Markdown = page.Slug, page.Title, page.Markdown
	return out, nil
}

// diagramInput names a generated diagram. Declared for the spec; the handler reads the path
// value itself and docs.Diagram refuses anything but a plain "<name>.svg".
type diagramInput struct {
	Name string `path:"name" example:"architecture.svg" doc:"The diagram's file name, as a help page references it"`
}

// serveDiagram writes one embedded diagram. The files are ours, generated by D2 from
// committed sources, but an SVG is a document that can carry script if it is ever opened on
// its own rather than through <img>. So the type is pinned (nosniff) and the response is
// sandboxed with no sources beyond its own inline styles and data: fonts and icons. Help
// renders it only through <img>, where script never runs anyway.
func serveDiagram(w http.ResponseWriter, r *http.Request) {
	body, ok := docs.Diagram(r.PathValue("name"))
	if !ok {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "image/svg+xml")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Content-Security-Policy",
		"default-src 'none'; style-src 'unsafe-inline'; img-src data:; font-src data:; sandbox")
	// The bytes change only with the binary, and Help is behind a sign-in.
	w.Header().Set("Cache-Control", "private, max-age=3600")
	http.ServeContent(w, r, "", time.Time{}, bytes.NewReader(body))
}

// screenshotInput names an embedded screenshot. Declared for the spec; the handler reads the
// path value itself and docs.Screenshot refuses anything but a plain "<name>-dark.webp".
type screenshotInput struct {
	Name string `path:"name" example:"guide-dark.webp" doc:"The screenshot's file name, as a help page references it"`
}

// serveScreenshot writes one embedded screenshot. A WebP is not a document, so it needs no
// sandbox; nosniff still pins the type.
func serveScreenshot(w http.ResponseWriter, r *http.Request) {
	body, ok := docs.Screenshot(r.PathValue("name"))
	if !ok {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "image/webp")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	// The bytes change only with the binary, and Help is behind a sign-in.
	w.Header().Set("Cache-Control", "private, max-age=3600")
	http.ServeContent(w, r, "", time.Time{}, bytes.NewReader(body))
}

type systemVersionOutput struct {
	Body struct {
		Version string `json:"version" example:"v0.3.1" doc:"Release tag, or 'dev' for an unstamped build"`
		Commit  string `json:"commit,omitempty"`
		BuiltAt string `json:"builtAt,omitempty"`
		Dirty   bool   `json:"dirty,omitempty" doc:"Built from a working tree with uncommitted changes"`
		Ready   bool   `json:"ready" doc:"Same readiness /v1/readyz reports"`
		Detail  string `json:"detail,omitempty" doc:"Why it is not ready"`

		// The About page's remaining rows (§16, V12) — what an operator quotes in a bug
		// report alongside the version.
		GoVersion string `json:"goVersion,omitempty" example:"go1.23.4" doc:"Go runtime this binary was built with"`
		Platform  string `json:"platform,omitempty" example:"linux/amd64" doc:"os/arch this process is running on"`
		// StartedAt is the process start as RFC3339 — NOT a pre-computed uptime. A
		// duration is stale the moment it is serialized; the client renders elapsed time
		// from this instant and can keep it current without re-fetching.
		StartedAt string `json:"startedAt,omitempty" doc:"When this process started (RFC3339); the UI derives uptime from it"`
		// SchemaVersion is the applied migration version. Omitted when unknown (0) rather
		// than sent as a real schema 0 — a wrong number in a bug report is worse than an
		// absent one.
		SchemaVersion int64  `json:"schemaVersion,omitempty" example:"20" doc:"Applied database migration version"`
		Backend       string `json:"backend,omitempty" example:"sqlite" doc:"Active database backend"`
	}
}

// systemVersion is the typed twin of /v1/readyz.
//
// ⚠ The old note here said the probes "deliberately stay OUTSIDE huma and unauthenticated…
// registering them would have put an auth requirement in front of a container health probe".
// The concern was right and its premise has since stopped holding: RolePublic marks an
// operation reachable with no credential, so /v1/healthz and /v1/readyz are Huma operations,
// still anonymous, with their bare paths kept as permanent aliases (ops.go).
//
// This endpoint is NOT redundant with them. It carries what an operator quotes in a bug
// report — version, commit, build time, Go runtime, os/arch, process start, applied schema
// version and backend — which is authenticated information a liveness probe has no business
// returning to an unauthenticated caller.

func (s *Server) systemVersion(_ context.Context, _ *struct{}) (*systemVersionOutput, error) {
	info := buildinfo.Get()
	out := &systemVersionOutput{}
	out.Body.Version, out.Body.Commit = info.Version, info.Commit
	out.Body.BuiltAt, out.Body.Dirty = info.BuiltAt, info.Dirty
	out.Body.GoVersion = runtime.Version()
	out.Body.Platform = runtime.GOOS + "/" + runtime.GOARCH
	out.Body.StartedAt = s.startedAt.UTC().Format(time.RFC3339)
	// Schema version and backend need the store. A store-less boot (§7 readiness) still
	// serves this endpoint — it is what an operator reads to find out WHY the install is
	// unhealthy — so both rows are simply absent rather than the handler failing.
	if s.store != nil {
		out.Body.SchemaVersion = store.SchemaVersion(s.store)
		out.Body.Backend = string(store.DialectOf(s.store))
	}
	out.Body.Ready, out.Body.Detail = true, ""
	if s.ready != nil {
		out.Body.Ready, out.Body.Detail = s.ready()
	}
	return out, nil
}
