package api_test

import (
	"net/http"
	"os"
	"regexp"
	"strings"
	"testing"
)

// Every /v1/playout route must refuse an unauthenticated caller — and this test finds the routes
// itself rather than being told them.
//
// #264 moved playout authorization out of seven handler bodies and into ONE middleware, attached
// by `streamOp` at registration. That is the right shape, but it makes enforcement POSITIONAL: a
// route registered any other way is served with no device-token check and nothing fails. The
// existing negative tests (TestPlayout_RejectsMissingOrWrongToken and friends) are a hand-written
// path list, so they prove today's routes and can say nothing about tomorrow's — the same
// hand-maintained-list drift that scripts/check-tags.sh and check-retired.sh exist for.
//
// So the route list is DERIVED from api/openapi.yaml, which is generated by `make openapi` and
// gated by `make openapi-verify`. A new playout route joins the spec by being registered, and
// therefore joins this guard, with no list to remember to update.
var playoutSpecPath = regexp.MustCompile(`^ {2}(/v1/playout/\S*):\s*$`)

// The two auth models a playout route may legitimately use. Streaming routes answer 404 on bad
// credentials on purpose (a wrong token must be indistinguishable from no route — see
// authorizePlayout); the admin telemetry routes are RoleAdmin and answer 401/403.
//
// 500 is deliberately NOT accepted. A handler that panics on an unauthenticated request has also
// "not served" it, but that is a bug, not a refusal, and would otherwise pass this test.
var refusalCodes = map[int]bool{
	http.StatusUnauthorized: true,
	http.StatusForbidden:    true,
	http.StatusNotFound:     true,
}

func TestEveryPlayoutRouteRefusesAnonymousCallers(t *testing.T) {
	paths := playoutPathsFromSpec(t)

	// ⚠ The channel MUST exist. Without it a streaming route 404s because the channel is
	// missing, which is the same status an auth refusal produces — the test would pass while
	// proving nothing about authorization. Seeding it means 404 can only come from the guard.
	srv, st := newPlayoutServer(t, playoutOpts{sessions: &fakePlayoutSessions{}})
	seedChannel(t, st, "ch1", "Channel One", 1, "internal")

	for _, path := range paths {
		concrete := strings.NewReplacer(
			"{id}", "ch1",
			"{asset}", "seg-0.ts",
		).Replace(path)

		// A new placeholder must not be silently skipped: an unsubstituted {param} would request
		// a literal path that 404s for the wrong reason and quietly report success.
		if strings.ContainsAny(concrete, "{}") {
			t.Errorf("spec path %q has a placeholder this test does not know how to fill.\n"+
				"  Add a substitution above — leaving it would exercise a literal path and pass "+
				"without ever reaching the route.", path)
			continue
		}

		resp := getPlayout(t, srv, concrete)
		if !refusalCodes[resp.StatusCode] {
			t.Errorf("GET %s with NO credentials returned %d.\n"+
				"  Every /v1/playout route must refuse an anonymous caller: streaming routes 404 "+
				"(via streamOp -> playoutAuthMiddleware), admin routes 401/403 (via withRole).\n"+
				"  A route registered outside streamOp gets neither.", concrete, resp.StatusCode)
		}
	}
}

// playoutPathsFromSpec reads the generated OpenAPI document rather than a Go list.
//
// ⚠ THIS GUARD IS ONLY AS COMPLETE AS THE SPEC, AND THE SPEC HAS ITS OWN PARALLEL LIST.
// `export.go` builds api/openapi.yaml from a register list separate from the one `api.go` mounts,
// so a playout route added to api.go alone would serve traffic and be INVISIBLE here — the guard
// would pass while the route it should have caught went unchecked. What closes that hole is
// TestRegisterListsMatchBetweenRouterAndExporter (export_parity_test.go), which fails when the
// two lists disagree; `GET /v1/playout/sessions` is the route that taught this the hard way.
// Weakening that test silently narrows this one. The two belong together.
//
// A line scan, not a YAML parse: gopkg.in/yaml.v3 is an INDIRECT dependency today and promoting
// it to a direct one is a design-doc §14 change for no gain here. The file is generated with
// stable formatting and `make openapi-verify` fails the build when it drifts, so its shape is not
// something a human edits by hand.
func playoutPathsFromSpec(t *testing.T) []string {
	t.Helper()

	body, err := os.ReadFile("../../api/openapi.yaml")
	if err != nil {
		t.Fatalf("read api/openapi.yaml: %v", err)
	}

	var paths []string
	for _, line := range strings.Split(string(body), "\n") {
		if m := playoutSpecPath.FindStringSubmatch(line); m != nil {
			paths = append(paths, m[1])
		}
	}

	// Without this, a formatting change in the generator makes the scan match nothing and the
	// test reports success against zero routes — a guard that also reports confidence. There are
	// nine playout paths today; seven is a floor low enough not to churn, high enough to catch a
	// broken scan.
	if len(paths) < 7 {
		t.Fatalf("found only %d /v1/playout path(s) in api/openapi.yaml (%v).\n"+
			"  The scan is probably broken, not the spec — this guard would pass against nothing.",
			len(paths), paths)
	}
	return paths
}
