const commonLanguages = [
  ["", "Any language"],
  ["en", "English"],
  ["es", "Spanish"],
  ["fr", "French"],
  ["de", "German"],
  ["it", "Italian"],
  ["pt", "Portuguese"],
  ["nl", "Dutch"],
  ["pl", "Polish"],
  ["ru", "Russian"],
  ["uk", "Ukrainian"],
  ["ar", "Arabic"],
  ["he", "Hebrew"],
  ["hi", "Hindi"],
  ["bn", "Bengali"],
  ["pa", "Punjabi"],
  ["ur", "Urdu"],
  ["zh", "Chinese"],
  ["ja", "Japanese"],
  ["ko", "Korean"],
  ["vi", "Vietnamese"],
  ["th", "Thai"],
  ["id", "Indonesian"],
  ["ms", "Malay"],
  ["tl", "Filipino"],
  ["tr", "Turkish"],
  ["el", "Greek"],
  ["sv", "Swedish"],
  ["no", "Norwegian"],
  ["da", "Danish"],
  ["fi", "Finnish"],
  ["cs", "Czech"],
  ["sk", "Slovak"],
  ["hu", "Hungarian"],
  ["ro", "Romanian"],
  ["bg", "Bulgarian"],
  ["hr", "Croatian"],
  ["sr", "Serbian"],
  ["sl", "Slovenian"],
  ["et", "Estonian"],
  ["lv", "Latvian"],
  ["lt", "Lithuanian"],
  ["is", "Icelandic"],
  ["ga", "Irish"],
  ["cy", "Welsh"],
  ["ca", "Catalan"],
  ["eu", "Basque"],
  ["gl", "Galician"],
] as const;

const languageName = (code: string): string =>
  commonLanguages.find(([value]) => value === code)?.[1] ?? code.toLocaleUpperCase();

export { commonLanguages, languageName };
