// Shared demo data — composites & lineage (Loomarr V45)
export const SINGLES = [
  { n: 'Nintendo Game Boy — “Play It Loud”', d: 30, kind: 'commercial', era: '1994', aud: 'kids', cat: 'tech', hue: 152, used: 'plays on CH 42 · auto' },
  { n: 'Trix — “Silly rabbit”', d: 15, kind: 'commercial', era: '1990', aud: 'kids', cat: 'cereal', hue: 12, used: 'plays on CH 42 · auto' },
  { n: 'Crossfire — “You’ll get caught up”', d: 30, kind: 'commercial', era: '1992', aud: 'kids', cat: 'toys', hue: 268, used: 'plays on CH 42 · auto' },
  { n: 'PSA — The More You Know', d: 20, kind: 'psa', era: '1994', aud: 'family', cat: 'psa', hue: 205, used: 'plays on CH 12, CH 42 · auto' },
  { n: 'Q13 FOX bumper — “Back after this”', d: 7, kind: 'bumper', era: '1996', aud: 'general', cat: 'bumper', hue: 38, used: 'pinned to CH 7 · 1 override' },
];

// seg: d(sec) n(name) b(brand) c(category) a(audience) conf(0-100) [drop] [why] [ok]
export const BREAKS = [
  {
    id: 'kcpq', filed: true, hue: 210,
    title: 'KCPQ/Fox commercials, 5/28/1996',
    network: 'FOX', station: 'KCPQ', market: 'SEATTLE', date: '5/28/1996', year: '1996',
    source: 'Internet Archive · vhs_commercials_kcpq_1996',
    segs: [
      { d: 5,  n: 'Q13 FOX ident', b: 'KCPQ', c: 'ident', a: 'general', conf: 96 },
      { d: 30, n: 'A&W Root Beer — “That frosty mug taste”', b: 'A&W', c: 'drinks', a: 'family', conf: 94 },
      { d: 31, n: 'US Navy — “Let the journey begin”', b: 'US Navy', c: 'psa', a: 'general', conf: 91 },
      { d: 15, n: 'Dove — “The litmus test”', b: 'Dove', c: 'household', a: 'general', conf: 88 },
      { d: 30, n: 'KFC — Colonel’s Crispy Strips', b: 'KFC', c: 'fast_food', a: 'family', conf: 93 },
      { d: 29, n: 'Snapple — “Made from the best stuff”', b: 'Snapple', c: 'drinks', a: 'general', conf: 90 },
      { d: 75, n: 'Mission: Impossible — trailer', b: 'Paramount', c: 'movie_trailer', a: 'general', conf: 97 },
      { d: 15, n: 'Reach toothbrush — “Bend it”', b: 'Reach', c: 'household', a: 'general', conf: 84 },
      { d: 30, n: 'Healthy Choice cereal', b: 'Healthy Choice', c: 'cereal', a: 'general', conf: 89 },
      { d: 16, n: 'Butterfinger — Christmas', b: 'Nestlé', c: 'candy', a: 'kids', conf: 77 },
      { d: 30, n: 'Dodge — Memorial Day sale event', b: 'Dodge', c: 'cars', a: 'general', conf: 95 },
      { d: 10, n: 'Q13 News at Ten — promo', b: 'KCPQ', c: 'promo', a: 'general', conf: 92 },
      { d: 30, n: 'McDonald’s — Arch Deluxe', b: 'McDonald’s', c: 'fast_food', a: 'general', conf: 96 },
      { d: 30, n: 'Pepsi — “Pepsi Stuff”', b: 'Pepsi', c: 'drinks', a: 'general', conf: 94 },
      { d: 30, n: 'Toyota Camry — “I love what you do for me”', b: 'Toyota', c: 'cars', a: 'general', conf: 90 },
      { d: 15, n: 'Blockbuster Video — “Wow, what a difference”', b: 'Blockbuster', c: 'retail', a: 'family', conf: 87 },
      { d: 30, n: 'AT&T True Voice', b: 'AT&T', c: 'telecom', a: 'general', conf: 88 },
      { d: 29, n: 'Mentos — “The Freshmaker”', b: 'Mentos', c: 'candy', a: 'general', conf: 93 },
      { d: 30, n: 'Got Milk? — dinner party', b: 'CMPB', c: 'psa', a: 'general', conf: 85 },
      { d: 31, n: 'Chevy Trucks — “Like a Rock”', b: 'Chevrolet', c: 'cars', a: 'general', conf: 92 },
      { d: 2,  n: 'Sliver — black frames', b: '', c: '', a: '', conf: 18, drop: true, why: 'no audio above −48 dB · 96% black pixels' },
      { d: 30, n: 'Sprint — “10¢ a minute”', b: 'Sprint', c: 'telecom', a: 'general', conf: 89 },
      { d: 15, n: 'Little Caesars — “Pizza! Pizza!”', b: 'Little Caesars', c: 'fast_food', a: 'family', conf: 91 },
      { d: 30, n: 'Budweiser — frogs', b: 'Budweiser', c: 'beer', a: 'late_night', conf: 86 },
      { d: 15, n: 'Seattle Mariners — ticket office promo', b: 'Mariners', c: 'local', a: 'general', conf: 83 },
      { d: 30, n: 'Les Schwab Tires — spring alignment', b: 'Les Schwab', c: 'local', a: 'general', conf: 79 },
      { d: 30, n: '1-800-COLLECT — “Save a buck or two”', b: 'MCI', c: 'telecom', a: 'general', conf: 87 },
      { d: 32, n: 'Windows 95 — “Start Me Up”', b: 'Microsoft', c: 'tech', a: 'general', conf: 90 },
      { d: 15, n: 'Fruitopia — “Fruit integration”', b: 'Coca-Cola', c: 'drinks', a: 'general', conf: 82 },
      { d: 30, n: 'Nike — Ken Griffey Jr. for President', b: 'Nike', c: 'apparel', a: 'general', conf: 88 },
      { d: 33, n: 'Weyerhaeuser — regional image spot', b: 'Weyerhaeuser', c: 'local', a: 'general', conf: 74 },
      { d: 15, n: 'The X-Files — tonight at 9 promo', b: 'KCPQ', c: 'promo', a: 'general', conf: 94 },
      { d: 15, n: 'Taco Time — Northwest original', b: 'Taco Time', c: 'local', a: 'family', conf: 76 },
      { d: 30, n: 'Ford Aerostar — “Have you driven a Ford lately?”', b: 'Ford', c: 'cars', a: 'family', conf: 89 },
      { d: 15, n: 'Kool-Aid — “Oh Yeah!”', b: 'Kraft', c: 'drinks', a: 'kids', conf: 90 },
      { d: 14, n: 'Squeezit — “Squeeze the fun out”', b: 'General Mills', c: 'drinks', a: 'kids', conf: 81 },
      { d: 15, n: 'PEMCO Insurance — “We’re a lot like you”', b: 'PEMCO', c: 'local', a: 'general', conf: 72 },
      { d: 15, n: 'Red Robin — gourmet burgers', b: 'Red Robin', c: 'fast_food', a: 'family', conf: 80 },
      { d: 3,  n: 'Sliver — tape glitch', b: '', c: '', a: '', conf: 22, drop: true, why: 'tracking noise between spots · no stable frame' },
      { d: 10, n: 'COPS — Tuesday promo', b: 'FOX', c: 'promo', a: 'late_night', conf: 91 },
      { d: 16, n: 'Duracell — “The Puttermans”', b: 'Duracell', c: 'household', a: 'general', conf: 86 },
      { d: 15, n: 'Payless ShoeSource — BOGO', b: 'Payless', c: 'retail', a: 'family', conf: 84 },
      { d: 5,  n: 'Q13 FOX ident — outro', b: 'KCPQ', c: 'ident', a: 'general', conf: 95 },
    ],
  },
  {
    id: 'wnbc', filed: true, hue: 330,
    title: 'WNBC commercials, Thanksgiving 1994',
    network: 'NBC', station: 'WNBC', market: 'NEW YORK', date: '11/24/1994', year: '1994',
    source: 'Drop folder · wnbc_thx_94.mpg',
    segs: [
      { d: 5,  n: 'NBC peacock ident', b: 'WNBC', c: 'ident', a: 'general', conf: 96 },
      { d: 30, n: 'Butterball — Turkey Talk-Line', b: 'Butterball', c: 'food', a: 'family', conf: 91 },
      { d: 30, n: 'Toys “R” Us — holiday catalog', b: 'Toys “R” Us', c: 'toys', a: 'kids', conf: 93 },
      { d: 30, n: 'Sears — Craftsman gift event', b: 'Sears', c: 'retail', a: 'general', conf: 89 },
      { d: 15, n: 'Campbell’s — “M’m! M’m! Good!”', b: 'Campbell’s', c: 'food', a: 'family', conf: 90 },
      { d: 30, n: 'AT&T — “You Will”', b: 'AT&T', c: 'telecom', a: 'general', conf: 88 },
      { d: 15, n: 'Folgers — holiday morning', b: 'Folgers', c: 'food', a: 'general', conf: 87 },
      { d: 10, n: 'Must See TV — Friends promo', b: 'NBC', c: 'promo', a: 'general', conf: 94 },
      { d: 30, n: 'JCPenney — doorbusters', b: 'JCPenney', c: 'retail', a: 'general', conf: 85 },
      { d: 15, n: 'Norelco — Santa sled', b: 'Norelco', c: 'household', a: 'family', conf: 82 },
      { d: 30, n: 'Pillsbury — crescent rolls', b: 'Pillsbury', c: 'food', a: 'family', conf: 90 },
      { d: 15, n: 'Chia Pet — “Ch-ch-ch-chia!”', b: 'Joseph Ent.', c: 'retail', a: 'family', conf: 79 },
      { d: 30, n: 'The Santa Clause — trailer', b: 'Disney', c: 'movie_trailer', a: 'family', conf: 95 },
      { d: 4,  n: 'Sliver — silence', b: '', c: '', a: '', conf: 19, drop: true, why: 'no audio · station clock card' },
      { d: 5,  n: 'WNBC 4 ident', b: 'WNBC', c: 'ident', a: 'general', conf: 93 },
    ],
  },
  {
    id: 'kiro', filed: false, hue: 190,
    title: 'KIRO/CBS commercials, 3/14/1997',
    network: 'CBS', station: 'KIRO', market: 'SEATTLE', date: '3/14/1997', year: '1997',
    source: 'Internet Archive · kiro7_breaks_mar97 · downloaded 12m ago',
    segs: [
      { d: 4,  n: 'KIRO 7 ident', b: 'KIRO', c: 'ident', a: 'general', conf: 95 },
      { d: 30, n: 'Toyota RAV4 — “A whole new species”', b: 'Toyota', c: 'cars', a: 'general', conf: 92 },
      { d: 29, n: 'McDonald’s — 2 for $2 Big Mac', b: 'McDonald’s', c: 'fast_food', a: 'general', conf: 94 },
      { d: 2,  n: 'Sliver — black frames', b: '', c: '', a: '', conf: 21, drop: true, why: 'no audio above −48 dB · mostly black frames' },
      { d: 17, n: 'Taco Bell — Star Wars glasses — pt 1', b: 'Taco Bell', c: 'fast_food', a: 'general', conf: 58, why: 'hard cut mid-spot — this may be one 0:30, not two' },
      { d: 13, n: 'Taco Bell — Star Wars glasses — pt 2', b: 'Taco Bell', c: 'fast_food', a: 'general', conf: 55, why: 'starts mid-scene · same brand as the previous cut' },
      { d: 30, n: 'Alaska Airlines — “For the same price, we’ll throw in the scenery”', b: 'Alaska Airlines', c: 'travel', a: 'general', conf: 90 },
      { d: 32, n: 'The Lost World: Jurassic Park — teaser', b: 'Universal', c: 'movie_trailer', a: 'general', conf: 96 },
      { d: 30, n: 'Rainier Beer — “Fresh from the mountains”', b: 'Rainier', c: 'beer', a: 'late_night', conf: 66, why: 'logo obscured — could be Rainier or Olympia' },
      { d: 15, n: 'Eddie Bauer — spring sale', b: 'Eddie Bauer', c: 'retail', a: 'general', conf: 71, why: 'brand read from end card only' },
      { d: 30, n: 'Got Milk? — “Aaron Burr”', b: 'CMPB', c: 'psa', a: 'general', conf: 89 },
      { d: 10, n: 'KIRO 7 News — sweeps promo', b: 'KIRO', c: 'promo', a: 'general', conf: 93 },
      { d: 30, n: 'Chevron — claymation cars', b: 'Chevron', c: 'cars', a: 'general', conf: 91 },
      { d: 30, n: 'Surge — “Feed the rush”', b: 'Coca-Cola', c: 'drinks', a: 'kids', conf: 87 },
      { d: 4,  n: 'KIRO 7 ident — outro', b: 'KIRO', c: 'ident', a: 'general', conf: 94 },
    ],
  },
];

export const ASKS = [
  { n: 'Trix — “Silly rabbit”', d: 15, hue: 12, conf: 71, why: 'brand certain · year ambiguous — the 1990 and 1992 cuts differ only in the last 2 seconds' },
  { n: 'Nintendo Game Boy — “Play It Loud”', d: 30, hue: 152, conf: 82, why: 'identical fingerprint to a clip already in the catalog — keep both or skip?' },
];
