// A two-second, 160×90 H.264 clip as an inline data URI — the story fixture for anything that
// renders a <video>.
//
// ⚠ **Inline, never a URL.** Stories must render offline and deterministically: the visual suite
// runs against `storybook-static` with no server behind it, so a story fetching `/v1/filler/media`
// would race the snapshot and flake. This repo has already been bitten by remote images in visual
// stories for exactly that reason.
//
// It is a flat `#1A222C` field with no motion, so a snapshot of a paused player is stable
// whichever frame the browser happens to have decoded. Generated with:
//
//   ffmpeg -f lavfi -i "color=c=0x1A222C:s=160x90:d=2:r=8" -c:v libx264 -pix_fmt yuv420p \
//     -movflags +faststart tiny.mp4
const TINY_MP4 =
  "data:video/mp4;base64," +
  "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAPzbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAB9AA";
("AQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
("AAAAAAAAAAAAAgAAAx10cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAB9AAAAAAAAAAAAAAAAAAAAAAAAEA");
("AAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAKAAAABaAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAfQ");
("AAAQAAABAAAAAAKVbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAABAAAAAgABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUA");
("AAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAACQG1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYA");
("AAAAAAAAAQAAAAx1cmwgAAAAAQAAAgBzdGJsAAAAwHN0c2QAAAAAAAAAAQAAALBhdmMxAAAAAAAAAAEAAAAAAAAAAAAA");
("AAAAAAAAAKAAWgBIAAAASAAAAAAAAAABFUxhdmM2Mi4yOC4xMDIgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAANmF2Y0MB");
("ZAAK/+EAGWdkAAqs2UKN+TARAAADAAEAAAMAEA8SJZYBAAZo6+PLIsD9+PgAAAAAEHBhc3AAAAABAAAAAQAAABRidHJ0");
("AAAAAAAAD0AAAAAAAAAAGHN0dHMAAAAAAAAAAQAAABAAAAgAAAAAFHN0c3MAAAAAAAAAAQAAAAEAAACIY3R0cwAAAAAA");
("AAAPAAAAAQAAEAAAAAABAAAoAAAAAAEAABAAAAAAAQAAAAAAAAABAAAIAAAAAAEAACgAAAAAAQAAEAAAAAABAAAAAAAA");
("AAEAAAgAAAAAAQAAKAAAAAABAAAQAAAAAAEAAAAAAAAAAQAACAAAAAABAAAgAAAAAAIAAAgAAAAAHHN0c2MAAAAAAAAA");
("AQAAAAEAAAAQAAAAAQAAAFRzdHN6AAAAAAAAAAAAAAAQAAAC6QAAABAAAAANAAAADQAAAA0AAAAWAAAADwAAAA0AAAAN");
("AAAAFgAAAA8AAAANAAAADQAAABYAAAAPAAAADQAAABRzdGNvAAAAAAAAAAEAAAQjAAAAYnVkdGEAAABabWV0YQAAAAAA");
("AAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAtaWxzdAAAACWpdG9vAAAAHWRhdGEAAAABAAAAAExhdmY2");
("Mi4xMi4xMDIAAAAIZnJlZQAAA9htZGF0AAACrQYF//+p3EXpvebZSLeWLNgg2SPu73gyNjQgLSBjb3JlIDE2NSByMzIy");
("MiBiMzU2MDVhIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAyNSAtIGh0dHA6Ly93d3cu");
("dmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFseXNl");
("PTB4MzoweDExMyBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3Jhbmdl");
("PTE2IGNocm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MSBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEg");
("Y2hyb21hX3FwX29mZnNldD0tMiB0aHJlYWRzPTMgbG9va2FoZWFkX3RocmVhZHM9MSBzbGljZWRfdGhyZWFkcz0wIG5y");
("PTAgZGVjaW1hdGU9MSBpbnRlcmxhY2VkPTAgYmx1cmF5X2NvbXBhdD0wIGNvbnN0cmFpbmVkX2ludHJhPTAgYmZyYW1l");
("cz0zIGJfcHlyYW1pZD0yIGJfYWRhcHQ9MSBiX2JpYXM9MCBkaXJlY3Q9MSB3ZWlnaHRiPTEgb3Blbl9nb3A9MCB3ZWln");
("aHRwPTIga2V5aW50PTI1MCBrZXlpbnRfbWluPTggc2NlbmVjdXQ9NDAgaW50cmFfcmVmcmVzaD0wIHJjX2xvb2thaGVh");
("ZD00MCByYz1jcmYgbWJ0cmVlPTEgY3JmPTIzLjAgcWNvbXA9MC42MCBxcG1pbj0wIHFwbWF4PTY5IHFwc3RlcD00IGlw");
("X3JhdGlvPTEuNDAgYXE9MToxLjAwAIAAAAA0ZYiEABL//ujJ/Mstazd0hVIYhWnHMI9HTDq9Ryj5DauJTJ32SFGV5K3V");
("VskBlwAGDBalcQAAAAxBmiRsQS/+tSqAHjAAAAAJQZ5CeIf/AElBAAAACQGeYXRDvwBoQAAAAAkBnmNqQ78AaEEAAAAS");
("QZpoSahBaJlMCCP//rUqgB4xAAAAC0GehkURLD//AElBAAAACQGepXRDvwBoQQAAAAkBnqdqQ78AaEAAAAASQZqsSahB");
("bJlMCCH//qpVADxgAAAAC0GeykUVLD//AElBAAAACQGe6XRDvwBoQAAAAAkBnutqQ78AaEAAAAASQZrvSahBbJlMCHf/");
("/qmWAOaBAAAAC0GfDUUVLDv/AGhBAAAACQGfLmpDvwBoQQ==");

export { TINY_MP4 };
