// Token generator (frontend-design §2.5). Emits three artifacts from tokens.ts —
//   1. generated/theme.css        — Tailwind v4 @theme variables (the web app)
//   2. generated/tailwind-preset.cjs — a Tailwind preset (web now, NativeWind later)
//   3. generated/tokens.json      — raw values for any non-Tailwind consumer
// — and VALIDATES every on-tint contrast pairing (§2.1). Output is deterministic
// (stable ordering, trailing newline) so `make fe-tokens` diffs are empty in CI.
//
// Run with: pnpm --filter @loomarr/tokens generate  (tsx src/generate/generate.ts)

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { AA_SMALL, compositeTint, contrast } from "../contrast";
import {
  accents,
  motion,
  radius,
  rowHeight,
  semanticAliases,
  space,
  staticExtras,
  staticScale,
  tintSteps,
  tintSurface,
  typography,
} from "../tokens";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "generated");
const HEADER = "/* GENERATED by @loomarr/tokens — edit src/tokens, run `make fe-tokens`. */";

// coreColors is the raw palette (statics + accents + -300 stops) — the only colors
// theme.css emits. The shadcn semantic layer (background/card/primary/border/…) is
// owned by the app (apps/web styles.css), so we keep the aliases OUT of theme.css
// to avoid a --color-primary collision; they remain in the preset + tokens.json.
const coreColors = (): Record<string, string> => {
  const out: Record<string, string> = { ...staticScale, ...staticExtras };
  for (const [name, a] of Object.entries(accents)) {
    out[name] = a.base;
    if (a.on !== a.base) out[`${name}-300`] = a.on; // the on-tint text stop (§2.1)
  }
  return out;
};

// allColors adds the semantic aliases (§2.1) — for the Tailwind preset + tokens.json.
const allColors = (): Record<string, string> => {
  const out = coreColors();
  for (const [alias, accent] of Object.entries(semanticAliases)) out[alias] = accents[accent].base;
  return out;
};

// contrast gate: every on-tint pairing must clear AA on the composited tint.
const validateContrast = (): string[] => {
  const report: string[] = [];
  for (const [name, a] of Object.entries(accents)) {
    if (a.on === a.base) continue; // no separate stop → nothing to prove here
    const tintBg = compositeTint(a.base, 15, tintSurface); // the 15% wash over the card
    const baseRatio = contrast(a.base, tintBg);
    const onRatio = contrast(a.on, tintBg);
    report.push(
      `  ${name}: base ${baseRatio.toFixed(2)} (needs the -300 stop) → -300 ${onRatio.toFixed(2)} on ${tintBg}`,
    );
    if (onRatio < AA_SMALL) {
      throw new Error(
        `contrast regression: ${name}-300 (${a.on}) is ${onRatio.toFixed(2)}:1 on the 15% tint ` +
          `${tintBg} — below the ${AA_SMALL}:1 AA bar. Fix the palette or the -300 stop (§2.1).`,
      );
    }
  }
  return report;
};

// theme.css (Tailwind v4 @theme).
const themeCss = (colors: Record<string, string>): string => {
  const lines: string[] = [HEADER, "", "@theme {"];
  lines.push("  /* colors */");
  for (const [k, v] of Object.entries(colors)) lines.push(`  --color-${k}: ${v};`);
  lines.push("", "  /* accent tints — alpha washes over the surface (§2.1) */");
  for (const [name] of Object.entries(accents))
    for (const step of tintSteps)
      lines.push(
        `  --color-${name}-tint-${step}: color-mix(in srgb, var(--color-${name}) ${step}%, transparent);`,
      );
  lines.push("", "  /* typography */");
  lines.push(`  --font-sans: ${typography.fonts.sans};`);
  lines.push(`  --font-mono: ${typography.fonts.mono};`);
  for (const [k, v] of Object.entries(typography.size)) lines.push(`  --text-${k}: ${v}px;`);
  lines.push(`  --leading-body: ${typography.leading.body};`);
  lines.push(`  --leading-heading: ${typography.leading.heading};`);
  lines.push("", "  /* space, radius */");
  for (const [k, v] of Object.entries(space)) lines.push(`  --spacing-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(radius)) lines.push(`  --radius-${k}: ${v}px;`);
  lines.push(`  --row-compact: ${rowHeight.compact}px;`);
  lines.push("", "  /* motion */");
  lines.push(`  --ease-out: ${motion.ease};`);
  for (const [k, v] of Object.entries(motion.duration)) lines.push(`  --duration-${k}: ${v};`);
  lines.push("}", "");
  return lines.join("\n");
};

// tailwind-preset.cjs (web + NativeWind); tints as rgba (RN has no color-mix).
const rgba = (hex: string, alphaPct: number): string => {
  const n = parseInt(hex.replace("#", ""), 16);
  return `rgba(${(n >> 16) & 0xff}, ${(n >> 8) & 0xff}, ${n & 0xff}, ${alphaPct / 100})`;
};

const tailwindPreset = (colors: Record<string, string>): string => {
  const colorObj: Record<string, string> = { ...colors };
  for (const [name, a] of Object.entries(accents))
    for (const step of tintSteps) colorObj[`${name}-tint-${step}`] = rgba(a.base, step);
  const preset = {
    theme: {
      extend: {
        colors: colorObj,
        spacing: Object.fromEntries(Object.entries(space).map(([k, v]) => [k, `${v}px`])),
        borderRadius: Object.fromEntries(Object.entries(radius).map(([k, v]) => [k, `${v}px`])),
        fontFamily: { sans: [typography.fonts.sans], mono: [typography.fonts.mono] },
        fontSize: Object.fromEntries(Object.entries(typography.size).map(([k, v]) => [k, `${v}px`])),
        transitionTimingFunction: { out: motion.ease },
        transitionDuration: motion.duration,
      },
    },
  };
  return `${HEADER}\nmodule.exports = ${JSON.stringify(preset, null, 2)};\n`;
};

const tokensJson = (colors: Record<string, string>): string =>
  `${JSON.stringify({ colors, space, radius, typography, motion, tintSteps }, null, 2)}\n`;

const main = (): void => {
  const report = validateContrast();
  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, "theme.css"), themeCss(coreColors()));
  writeFileSync(join(OUT, "tailwind-preset.cjs"), tailwindPreset(allColors()));
  writeFileSync(join(OUT, "tokens.json"), tokensJson(allColors()));
  console.log("tokens: wrote theme.css, tailwind-preset.cjs, tokens.json");
  console.log("contrast (on-tint pairings pass AA on the composited 15% tint):");
  console.log(report.join("\n"));
};

main();
