import { describe, expect, it } from "vitest";

import {
  Action,
  ActivityIndicator,
  ArtworkFrame,
  Badge,
  BrandLaunch,
  BrandLockup,
  BrandMark,
  BrandWordmark,
  brandContract,
  ChoiceGroup,
  Field,
  FocusSurface,
  Icon,
  iconography,
  icons,
  LoomarrProvider,
  ProgressTrack,
  resolveViewportInsets,
  Screen,
  SignalLoader,
  Skeleton,
  Surface,
  semanticColors,
  Text,
  Toggle,
  typography,
} from "../index";

describe("design-system public interface", () => {
  it("exposes semantic values and universal primitives without Tamagui leaking to callers", () => {
    expect([
      LoomarrProvider,
      ActivityIndicator,
      Action,
      Screen,
      Surface,
      FocusSurface,
      Field,
      Toggle,
      ChoiceGroup,
      Text,
      Badge,
      ArtworkFrame,
      ProgressTrack,
      resolveViewportInsets,
      SignalLoader,
      Skeleton,
      BrandMark,
      BrandWordmark,
      BrandLockup,
      BrandLaunch,
      brandContract,
      Icon,
      icons.play,
      iconography,
      semanticColors,
      typography,
    ]).not.toContain(undefined);
  });
});
